### ISSUE TITLE
[USUÁRIOS - BACK] Upgrade no CRUD de usuários

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-users-microservice#2]
🚀 Cadastro e login de usuários
---
O cliente deseja cadastro de 3 tipos de usuários: "comum", "suporte" e "administrador", para que cada perfil tenha suas funcionalidades personalizadas. 
>💡 Esta tarefa se refere ao upgrade do microsserviço de usuários para exclusão e atualização de dados de usuários

#### Expectativa de finalização
Microsserviço atualizado com funcionalidade de exclusão e alteração de dados de usuário.

#### Solução proposta
- [x] Atualizar rotas para adaptação à exclusão de usuários
- [x] Atualizar rotas para adaptação à edição de dados de usuário

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [ ] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by GabrielCamargoL** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:
Foram utilizadas as seguintes tecnologias durante o CRUD de usuários: Java 11, Spring 2.6.6, Imsomnia, VS Code.

### 📸 Print do atualizador de usuários, contendo os campos: 
- firstName
- lastName
- email
- role
- updatedAt 

![image](https://user-images.githubusercontent.com/55204419/165425942-d6856487-f25b-4b73-a24b-0747470369fe.png)
