### ISSUE TITLE
[BACK] Cadastro de equipamentos

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-users-microservice#4]
🚀 Cadastro de equipamentos
---
O cliente deseja cadastro de equipamentos para acompanhar seus problemas, frequências e impactos.
>💡 Esta tarefa se refere ao cadastro de novos equipamentos

#### Expectativa de finalização
Funcionalidade de cadastro de equipamentos, com atributos simples settados no modelo de dados descritos no [Whimsical](https://whimsical.com/helpduck-documentacao-LCQyL3MY2kMSDYvauvYSBe).

#### Solução proposta
- [x] Criação de funcionalidade para cadastro de equipamentos
<div align="center">

| VERBO                                           | ROTA                                    | AÇÃO                             |
|:----------------------------------------------|:--------------------------------------|:---------------------------------|
|  [![image](https://img.shields.io/badge/POST-4682B4?style=for-the-badge)]()  | `/equipments/create` | criação de novo equipamento |
</div>

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [ ] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by Nepoun** [comment]
Alteração no crud do equipamento;
- Adição da função para cadastro de equipamentos
- Utiliza PostMapping com "equipments/create"
