### ISSUE TITLE
[BACK] Atualização de equipamentos

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-users-microservice#8]
🚀 Cadastro de equipamentos
---
O cliente deseja cadastro de equipamentos para acompanhar seus problemas, frequências e impactos.
>💡 Esta tarefa se refere à atualização do registro de equipamentos

#### Expectativa de finalização
Funcionalidade de atualização de equipamentos através de um endpoint que altera informações de um equipamento específico.

#### Solução proposta
- [x] Criação de funcionalidade para alteração de equipamentos
<div align="center">

| VERBO                                           | ROTA                                    | AÇÃO                             |
|:----------------------------------------------|:--------------------------------------|:---------------------------------|
| [![image](https://img.shields.io/badge/PUT-9370DB?style=for-the-badge)]() | `/equipments/update` | atualiza um equipamento |
</div>

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [ ] Code Review (abertura e aprovação de PR)
- [ ] Validação do cliente (caso necessário)

**Comment by Nepoun** [comment]
Alteração no crud do equipamento;
- Adição da função para atualizar equipamentos
- Utiliza PutMapping com "equipments/update"
